CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(30)                             NOT NULL,
    description VARCHAR(300),
    completed   BOOLEAN                                 NOT NULL,
    created_at  date                                    NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);